name: servicehub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.6.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  ionicons: ^0.2.2  # Tambahkan dependensi ionicons untuk ikon
  http: ^1.3.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  in_app_review: ^2.0.6
  ionicons: ^0.2.2


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/Logo_app.png
  android_gravity: center
  android_12:
    image: assets/icons/Logo_app.png
    color: "#FFFFFF"
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgroundSpalsh.png
    - assets/icons/Logo_app.png
    - assets/images/backgroundSpalshWhite.png
    - assets/icons/Addres.png
    - assets/icons/Buyer.png
    - assets/icons/Worker.png
    - assets/images/detail.png
    - assets/images/eh.png
    - assets/images/hc.png
    - assets/icons/cod.png
    - assets/icons/bank_transfer.png
    - assets/icons/qris.png
    - assets/images/cleaning.png
    - assets/images/painting.png
    - assets/images/elh.png
    - assets/images/paint.png
    - assets/images/plumb.png
    - assets/icons/rizal.png
    - assets/icons/agung.png
    - assets/icons/daffa.png
    - assets/icons/putri.png
    - assets/images/about_us.png
    - assets/icons/teknisi.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
